# Generated by Django 4.1.3 on 2022-11-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitap',
            options={'verbose_name': 'Kitap', 'verbose_name_plural': 'Kitaplar'},
        ),
        migrations.AlterModelOptions(
            name='yazar',
            options={'verbose_name': 'Yazar', 'verbose_name_plural': 'Yazarlar'},
        ),
    ]
